CREATE TABLE IF NOT EXISTS Homework
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS Lesson
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    updatedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    homework_id INT,
    FOREIGN KEY (homework_id) REFERENCES Homework (id)

);

CREATE TABLE IF NOT EXISTS Schedule
(
    id        SERIAL PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schedule_lesson
(
    schedule_id INT NOT NULL,
    lesson_id   INT NOT NULL,
    PRIMARY KEY (schedule_id, lesson_id),
    FOREIGN KEY (schedule_id) REFERENCES Schedule (id) ON DELETE CASCADE,
    FOREIGN KEY (lesson_id) REFERENCES Lesson (id) ON DELETE CASCADE
);
